# Grantmaker settings
foundation_name: Peaceful Mind 
foundation_tagline: Promoting community resilience and wellness for all.

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
# profile_twitter: https://twitter.com/examplefdn
# profile_facebook: https://facebook.com/the-example-foundation
# profile_instagram: 
# profile_github: 

# Site settings
title: # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  Peaceful Mind is dedicated to promoting community resilience and wellness through strategic philanthropy and partnerships. We believe in empowering communities to thrive by supporting charity initiatives in developing countries.
# Google settings
live: false # enter 'true' when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
baseurl: "" # Leave blank unless you are using a subdirectory (e.g. /blog)
url: https://smartergiving.org # Typically http://www.yourdomain.org
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
  - vendor/**
